const products=[
{name:'Mori Ceramic Mug',category:'Home',price:38,tag:'New',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=700&q=80'},
{name:'Field Notes Tote',category:'Carry',price:64,tag:'Bestseller',image:'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=700&q=80'},
{name:'Arc Candle Holder',category:'Objects',price:42,tag:'New',image:'https://images.unsplash.com/photo-1602874801006-e26d8bfe35d3?auto=format&fit=crop&w=700&q=80'},
{name:'Stillness Throw',category:'Home',price:110,tag:'',image:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=700&q=80'},
{name:'Daily Carry Pouch',category:'Carry',price:28,tag:'',image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=80'},
{name:'Sora Glass Carafe',category:'Home',price:58,tag:'New',image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=700&q=80'},
{name:'Sunday Incense Set',category:'Objects',price:24,tag:'',image:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=700&q=80'},
{name:'Ridge Desk Tray',category:'Objects',price:46,tag:'',image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=700&q=80'}
];
let cart=[];const $=s=>document.querySelector(s),grid=$('#product-grid');const formatBDT=value=>`৳${(Number(value||0)*100).toLocaleString('en-BD')}`;
function renderProducts(category='All',query=''){const filtered=products.filter(p=>(category==='All'||p.category===category||(category==='New arrivals'&&p.tag==='New'))&&`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()));grid.innerHTML=filtered.map(p=>`<article class="product-card"><div class="product-photo"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.tag?`<span class="product-tag">${p.tag}</span>`:''}<button class="quick-add" data-add="${products.indexOf(p)}">+</button></div><div class="product-info"><h3>${p.name}<span class="price">${formatBDT(p.price)}</span></h3><p>${p.category} / Mynuverse studio</p></div></article>`).join('')||'<p class="empty-cart">No objects found. Try another search.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(Number(b.dataset.add))))}
function addToCart(index){const existing=cart.find(item=>item.product.id===products[index].id);if(existing)existing.quantity+=1;else cart.push({product:products[index],quantity:1});renderCart();openDrawer('cart')}
function cartTotal(){return cart.reduce((sum,item)=>sum+item.product.price*item.quantity,0)}
function renderCart(){const totalQuantity=cart.reduce((sum,item)=>sum+item.quantity,0);$('#bag-count').textContent=totalQuantity;$('#drawer-count').textContent=totalQuantity;$('#cart-total').textContent=formatBDT(cartTotal());$('#cart-items').innerHTML=cart.length?cart.map((item,index)=>`<div class="cart-item"><img src="${item.product.image}" alt=""><div><strong>${item.product.name}</strong><small>${item.product.category||'Mynuverse collection'}</small><div class="quantity-control"><button data-decrease="${index}" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button data-increase="${index}" aria-label="Increase quantity">+</button></div></div><b>${formatBDT(item.product.price*item.quantity)}</b><button data-remove="${index}" aria-label="Remove item">×</button></div>`).join(''):'<div class="empty-cart">Your bag is waiting.<br><span>Add something considered.</span></div>';document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart.splice(Number(b.dataset.remove),1);renderCart()}));document.querySelectorAll('[data-increase]').forEach(b=>b.addEventListener('click',()=>{cart[Number(b.dataset.increase)].quantity+=1;renderCart()}));document.querySelectorAll('[data-decrease]').forEach(b=>b.addEventListener('click',()=>{const item=cart[Number(b.dataset.decrease)];item.quantity-=1;if(item.quantity<1)cart.splice(Number(b.dataset.decrease),1);renderCart()}))}
function openDrawer(type){closeDrawers();$('#scrim').classList.add('visible');$(`#${type}-drawer`).classList.add('open')}function closeDrawers(){$('#scrim').classList.remove('visible');document.querySelectorAll('.search-drawer,.cart-drawer,.order-drawer').forEach(d=>d.classList.remove('open'))}document.addEventListener('click',event=>{if(event.target.id==='scrim'||event.target.closest('#bag-close,#order-close,#search-close'))closeDrawers()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDrawers()});
function showCategory(category){if($('#admin-view').classList.contains('active-view'))return;renderProducts(category);$('#collection').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>showCategory(b.dataset.category)));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{$('#store-view').classList.add('active-view');$('#admin-view').classList.remove('active-view');window.scrollTo(0,0)}));
$('#admin-toggle').addEventListener('click',()=>{$('#store-view').classList.remove('active-view');$('#admin-view').classList.add('active-view');window.scrollTo(0,0)});$('#back-store').addEventListener('click',()=>{$('#admin-view').classList.remove('active-view');$('#store-view').classList.add('active-view');window.scrollTo(0,0)});$('#bag-open').addEventListener('click',()=>openDrawer('cart'));$('#bag-close').addEventListener('click',closeDrawers);$('#scrim').addEventListener('click',closeDrawers);$('#search-toggle').addEventListener('click',()=>{openDrawer('search');$('#search-input').focus()});$('#search-close').addEventListener('click',closeDrawers);$('#search-input').addEventListener('input',e=>renderProducts('All',e.target.value));$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();$('#newsletter-message').textContent='You are on the list. See you soon.';e.target.reset()});
async function loadCatalog(){try{const response=await fetch('/api/products');const data=await response.json();if(data.products?.length){products.length=0;products.push(...data.products.map(product=>({...product,tag:product.featured?'Bestseller':''})));}renderProducts();renderCart()}catch(error){renderProducts();renderCart()}}
function renderOrderReview(){const review=$('#order-review');review.innerHTML=cart.map(item=>`<div class="order-review-row"><span>${item.product.name} × ${item.quantity}</span><strong>${formatBDT(item.product.price*item.quantity)}</strong></div>`).join('')+`<div class="order-review-row order-review-total"><span>Order total</span><strong>${formatBDT(cartTotal())}</strong></div>`}
async function openOrderReview(){if(!cart.length)return;const session=await fetch('/api/auth/session');if(!session.ok){$('#order-status').className='order-status';$('#order-status').innerHTML='Please <a href="/account.html">sign in or create an account</a> before confirming your order.';openDrawer('order');return}const data=await session.json();$('#order-form [name="shippingName"]').value=data.user.name;renderOrderReview();openDrawer('order')}
async function confirmOrder(event){event.preventDefault();const status=$('#order-status');status.className='order-status';status.textContent='';try{const session=await fetch('/api/auth/session');if(!session.ok)throw new Error('Please sign in before confirming your order.');const sessionData=await session.json();const payload={items:cart.map(item=>({productId:item.product.id,quantity:item.quantity})),shippingName:event.target.shippingName.value,shippingPhone:event.target.shippingPhone.value,shippingAddress:event.target.shippingAddress.value};const response=await fetch('/api/orders/confirm',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':sessionData.csrfToken},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to confirm order.');status.className='order-status success';status.textContent=`Order ${data.orderNumber} confirmed. We will review it shortly.`;cart=[];renderCart()}catch(error){status.textContent=error.message}}
$('#admin-products').innerHTML=products.slice(0,4).map(p=>`<div class="best-product"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><small>${Math.floor(Math.random()*30+20)} sold this month</small></div><b>${formatBDT(p.price)}</b></div>`).join('');$('#review-order').addEventListener('click',openOrderReview);$('#order-close').addEventListener('click',closeDrawers);$('#order-form').addEventListener('submit',confirmOrder);loadCatalog();
